"use client"
import "./globals.css";
// import { Inter } from "next/font/google";
import { MuiNavbar } from "./components/MuiNavbar";
import styles from './page.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { usePathname } from 'next/navigation'
import React from "react";
import { useRouter } from 'next/navigation'



// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const pathname  = usePathname();
  const routesWithoutNavbar = ['/pages/useraccess', '/'];
  const showNavbar = !routesWithoutNavbar.includes(pathname);

  React.useEffect(() => {
    const token = sessionStorage.getItem('TOKEN');
    if (!token) {
      // If the token does not exist, redirect to the login page
      return router.push('/pages/useraccess');
    }

  }, [router])

  return (
    <html lang="en">
      <body>
        {  showNavbar && <MuiNavbar /> }

        <main className={styles.main}>

            { children }

        </main>
      </body>
    </html>
  );
}

